### ISSUE TITLE
Quilt says it doesnt support hashed mappings and asks me to update when i'm on the newest version of quilt. (i have no idea what im doing)

### ISSUE THREAD

**Issue by honey-bbq-sauce** [LemmaEOF/mc-aprilfools-2022#2]
I don't have much information to give but I was using the latest version of quilt available for 22w13obaat on atlauncher that may be an issue and qsl isn't available for 22w13 to my knowledge and wasn't present.
 
crash report is attached instead of pasted because markdown was messing with it
[crash-2023-07-28_23.16.24.6222-quilt_loader.txt](https://github.com/LemmaEOF/mc-aprilfools-2022/files/12198851/crash-2023-07-28_23.16.24.6222-quilt_loader.txt)
thanks for the help in advance

**Comment by LemmaEOF** [comment]
Yeah, this is just because Quilt didn't do an update for One Block At A Time. Not something I can fix.
